version: '2'
services: 
  db: 
    image: postgres
    container_name: werails_db
  web: 
    build: .    
    container_name: werails_web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
       - .:/app
    ports: 
       - "8080:3000"
    depends_on:
       - db
    environment:
      - DOCKERIZED=true
    env_file:
      - .env